### ISSUE TITLE
Anonymizing

### ISSUE THREAD

**Issue by ManuLpz4** [realdiganta/Contact-Tracing-App-TracerX#2]
I think tou can (and should) anonymizing the data (not only the user view, really anonymizing) using other data source like bluetooth or wifi closeness between users.
If you need whatever, count with me :)

**Comment by dxganta** [comment]
Actually I also had data annoymizing in mind too but couldn't wrap my head around how to do it. Please send me a mail here digantakalita.ai@gmail.com and lets discuss it.

**Comment by ManuLpz4** [comment]
Sent :)
